### ISSUE TITLE
ctx.isNewInstance not supported for 'before|after save' operation hooks on instance.save()?

### ISSUE THREAD

**Issue by notbrain** [strongloop/loopback-connector-mysql#106]
I am seeing ctx.isNewInstance = undefined/true on an existing instance save. My script just loads all Person entities, then loops over and updates a single attrib value. Works fine when I use `.updateAttribute()` but it should work for `.save()` since I'm calling a function on an instance with an ID.

Versions:

```
"loopback": "^2.18.0",
"loopback-boot": "^2.8.1",
"loopback-connector-mongodb": "^1.11.1",
"loopback-connector-mysql": "^2.1.1",
"loopback-datasource-juggler": "^2.30.0",
```

My update script:

```
Person.find(function(err, everyone) {
  if(err) {
    console.log(err);

  } else {
    var cnt = 0;

    _.forEach(everyone, function(person) {

      console.log(person); // id is present!

      var existingHash = person.hash;

      person.hash = getHash(person.email);

      person.save(function(err, personSaved) {
        if(err) {console.log(err);}

        cnt += 1;

        if(cnt === everyone.length) {
          mysqlDS.disconnect();
          process.exit(0);
        }

      });

    });

  }

});
```

My before save hook:

```
Person.observe('before save', function(ctx, next) {

  console.log('[before save] ctx.isNewInstance', ctx.isNewInstance);

  next();

});
```

My after save hook:

```
Person.observe('after save', function(ctx, next) {

  console.log('[after save] ctx.isNewInstance', ctx.isNewInstance);

  next();

});
```

Output when I run the script:

```
[before save] ctx.isNewInstance undefined
[after save] ctx.isNewInstance true
```

Shouldn't these both (explicitly) be false when calling `.save()` on a person entity with an id?

**Comment by jduhls** [comment]
Seeing same thing. ".isNewInstance" is always true in "after save".
```javascript
module.exports = function(Alert) {
    Alert.observe('before save', function(context, next) {
        if (context.instance) {
            if(typeof context.isNewInstance != 'undefined' && context.isNewInstance) {
                logger.log('Saving new %s', context.Model.modelName);
            } else {
                logger.log('Updating %s matching %j',
                    context.Model.pluralModelName,
                    context.where);
            }
        } else {
            logger.log('Updating %s matching %j',
                context.Model.pluralModelName,
                context.where);
        }
        next();
    });

    Alert.observe('after save', function(context, next) {
        if (context.instance) {
            if(typeof context.isNewInstance != 'undefined' && context.isNewInstance) {
                logger.log('Saved %s #%s', context.Model.modelName, context.instance.id);
            } else {
                logger.log('Updated %s matching %j',
                    context.Model.pluralModelName,
                    context.where);
            }
        } else {
            logger.log('Updated %s matching %j',
                context.Model.pluralModelName,
                context.where);
        }
        next();
    });
};
```

**Comment by ShaharHD** [comment]
+1 same here

**Comment by recallfx** [comment]
I had similar issue with `upsert`. If none of the properties was updated, `isNewInstance` would always be true. For reference see mysql.js (line 247):

```
        meta.isNewInstance = (info.affectedRows === 1);
```

The workaround was to introduce at least one field that always changes: 

```
    message.observe('before save', function updateTimestamp(ctx, next) {
        if (ctx.instance) {
            ctx.instance.msgUpdated = new Date();
        } else {
            ctx.data.msgUpdated = new Date();
        }
        next();
    });
```

**Comment by bekoli** [comment]
@recallfx: Close. I debugged this quite some time today since I run into the very same issue.

Here's the important part from line 237: https://github.com/strongloop/loopback-connector-mysql/blob/955f5dc084eea94a43a479d27591e26bb650e3d9/lib/mysql.js 

```
        // When using the INSERT ... ON DUPLICATE KEY UPDATE statement,
        // the returned value is as follows:
        // 1 for each successful INSERT.
        // 2 for each successful UPDATE.
      meta.isNewInstance = (info.affectedRows === 1);
```

And here is http://dev.mysql.com/doc/refman/5.6/en/insert-on-duplicate.html (installed on my current system)

> With ON DUPLICATE KEY UPDATE, the affected-rows value per row is 1 if the row is inserted as a new row, 2 if an existing row is updated, and 0 if an existing row is set to its current values

However, there's an appendix:

> If you specify the CLIENT_FOUND_ROWS flag to mysql_real_connect() when connecting to mysqld, the affected-rows value is 1 (not 0) if an existing row is set to its current values.

I sunk quite some hours in debugging this at this point and here is what I found in `./node_modules/mysql/lib/protocol/constants/client.js`:

> exports.CLIENT_FOUND_ROWS        = 2; /* Found instead of affected rows */

So this is what happens when you save() _with the very same data that is already in the database_ (use  DEBUG=loopback:connector:mysql to see this). Eyes on `affectedRows`:

>   loopback:connector:mysql Data:  OkPacket {
fieldCount: 0,
affectedRows: 1,
insertId: 0,
serverStatus: 2,
warningCount: 0,
message: '',
protocol41: true,
changedRows: 0 } +1ms

Removed `exports.CLIENT_FOUND_ROWS` from `./node_modules/mysql/lib/protocol/constants/client.js` and tried again:

>  loopback:connector:mysql Data:  OkPacket {
  fieldCount: 0,
  affectedRows: 0,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '',
  protocol41: true,
  changedRows: 0 } +1ms

So here is what happens @notbrain: You ran this snippet before and your hash was already set. It worked basically once. CLIENT_FOUND_ROWS is probably set for you as well so `affectedRows` gets shifted from 0 to 1 and loopback-connector-mysql reads this as new instance.

This works fine for `updateAttributes` because in that case strongloop/loopback-datasource-juggler/commits/2.x-latest/lib/dao.js simply _enforces_ isNewInstance, like in all other cases, with a sane Boolean. `save()` is the only function where `result.isNewInstance` by loopback-connector-mysql is consulted at all.

Thing is: mysqljs/mysql@59a1a705f5ac367dc3768985940b81e60ee23884 , that shifted CLIENT_FOUND_ROWS from config to client.js, was last changed on Sep 2012.

Did this ever work before? Or was CLIENT_FOUND_ROWS usually unset somehow again? Is there a test for setting an existing row to its current values and check for `affectedRows`?

@bajtos to my aid. I've no clue for the best course of action on fixing this nasty or whether mysql.js or some missing ENV is to blame.

**Comment by bajtos** [comment]
@bekoli first of all, thank you for such in-depth analysis and a detailed description! To be honest, I am not intimately familiar with this connector (and MySQL in general), but I'll try to take a closer look and help. It may not happen this year though, as the Holidays are around the corner.

@strongloop/squad-apex can one of you take a look please?

**Comment by bekoli** [comment]
@bajtos No sweat. I just had the idea that you're involved in such issues since you do a lot of sorting/referencing/commit work on Loopback and I have simply no idea who is to bug with this.

**Comment by b-admike** [comment]
@bajtos @bekoli I have started working on this issue and so far tried to use the following solutions:

 - Use [REPLACE](https://dev.mysql.com/doc/refman/5.6/en/replace.html) statements for `replaceOrCreate`(PUT) method in the connector. Unfortunately, we run into a similar issue where affected rows are 1 for a CREATE (if row doesn't exist) and a REPLACE with same values for the row. Thus, we cannot use the affected rows value to determine value of `isNewInstance`.

 - Turn off `CLIENT_FOUND_ROWS` as described [here](https://github.com/mysqljs/mysql#example) for our connector by default. This would make our current implementation work, but juggler tests downstream treat affected row count of 0 as an instance not found, instead of a current row being set to its existing values. These tests run for all connectors, so I'm a bit hesitant to use this approach. There might be other implications here that I might not be aware of. 

I haven't tried the following, but it is worth noting:
 - Do a check on the row to see if it exists before running replace/update or create. This way, we can set the `isNewInstance` value according to our first query. However, the downside to this is that the query is overhead and affects performance.

**Comment by bajtos** [comment]
First of all, I think `isNewInstance: undefined` is appropriate inside a "before save" hook, because the `save()` operation cannot reliably tell whether a new record is going to be created. Please correct me if I am wrong.

As for "after save" hook, I believe other connectors are able to provide this information, thus the task here is to figure out how to get this data from MySQL.

> Turn off CLIENT_FOUND_ROWS as described here for our connector by default. This would make our current implementation work, but juggler tests downstream treat affected row count of 0 as an instance not found, instead of a current row being set to its existing values. These tests run for all connectors, so I'm a bit hesitant to use this approach. There might be other implications here that I might not be aware of.

If the connector explicitly turns off `CLIENT_FOUND_ROWS`, then I'd expect the connector to clear "affected row count" property too, and report `undefined` instead. IIRC, juggler should be handling that in a reasonable way (but I may be wrong).

> Do a check on the row to see if it exists before running replace/update or create. This way, we can set the `isNewInstance` value according to our first query. However, the downside to this is that the query is overhead and affects performance.

This creates a race condition. When the application is under heavier load and multiple clients are trying to create the same record, then we may report incorrect `isNewInstance` value if the timing is wrong.

```
request1 checks whether the row exists (answer: no)
request2 checks whether the row exists (answer: no)
one of the requests performs replaceOrCreate (row is created)
the other of the requests performs replaceOrCreate (row is updated)
```

In my personal opinion, if we cannot find a reliable way how to accurately get the information from MySQL whether a new row was created or an existing row was updated, then we should keep reporting `undefined`.

**Comment by b-admike** [comment]
@bajtos I agree that "before save" hook should definitely be undefined for `save()`. I will look into how other connectors provide the same information, and pursue turning off `CLIENT_FOUND_ROWS` further. So far, the proper channels IMO to get the information from MySQL have not been reliable, so we might end up reporting `undefined` for "after save" hook.

**Comment by b-admike** [comment]
@notbrain Unfortunately, we cannot reliably tell whether a new row was created or an existing one was updating from MySQL, so I've disabled support for `ctx.isNewInstance` for 'after save' operation hook on `save()` for this connector.
