### ISSUE TITLE
missing Loopback Array type mapping 

### ISSUE THREAD

**Issue by ezraroi** [strongloop/loopback-connector-mysql#119]
in the list of Loopback types mapping to mysql types in the documentations, the Array type is missing

**Comment by jannyHou** [comment]
@ezraroi I am not sure how would we map `array` to mysql type since it doesn't support `array`, some doc find from mysql doc which might help, about how to store array in mysql:
http://99webtools.com/blog/how-to-store-array-in-mysql/

I label it as a feature but doubt is it a correct direction to deal with loopback `array` in mysql connector.
@raymondfeng would have a better understanding:)  any thought?

**Comment by ssh24** [comment]
Our connector serializes the array data before inserting into the database. Since mysql **does not support** array data type, we stringify the data and insert into the database. Upon getting the data back from the database, we convert it into an array.

Here is an example code snippet:
**model-definition.json**
```json
{
  "name": "League",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "teams": {
      "type": [
        "string"
      ]
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var assert = require('assert');
var util = require('util');
var _ = require('lodash');

module.exports = function(app) {
  var db = app.dataSources.mysqlDs;
  var League = app.models.League;

  db.automigrate(function(err) {
    if (err) throw err;
    console.log('\nAutomigrate complete');

    League.create([{
      name: 'EPL',
      teams: ['Liverpool', 'Arsenal', 'Manchester United', 'Chelsea'],
    }, {
      name: 'La Liga',
      teams: ['Barcelona', 'Real Madrid', 'Atletico Madrid'],
    }], function(err, result) {
      if (err) throw err;
      console.log('\nCreated instance: ' + util.inspect(result, 4));

      League.find(function(err, result) {
        if (err) throw err;
        console.log('\nFound instance: ' + util.inspect(result, 4));

        _.forEach(result, function(res) {
          assert(Array.isArray(res.teams));
        });
      });
    });
  });
};
```

Hope this answers your question.

Closing this issue. Feel free to reopen if needed.
