### ISSUE TITLE
Count does not support where like

### ISSUE THREAD

**Issue by Kr0san89** [strongloop/loopback-connector-mysql#121]
Hello,

using like in where clause at normal Model.find() works fine but using the same parameter on a count request it is not working any more. I would need it for pagination.

Here is the Code
```
        Customer.app.models.Customer.find({
          where: {firstname: {like: value + "%"}},
          skip: start,
          limit: limit
        }, function (err, customer) {
          sync(err, customer);
        });
        Customer.app.models.Customer.count({where: {firstname: {like: value + "%"}}}, function (err, count) {
          sync(err, null, count);
        });
```

Which Results in SQL (DEBUG=*mysql)
loopback:connector:mysql SQL: SELECT ... FROM `customer` WHERE `firstname` LIKE ? ORDER BY `id` LIMIT 25, params: ["M%"] +1ms
  loopback:connector:mysql SQL: SELECT count(*) as "cnt" FROM `customer` WHERE `where`?, params: [{"like":"M%"}] +1ms

Like it is visible in 2nd row the like parameter got parsed wrong.

Have you any ideas?
thanks

**Comment by saystone** [comment]
You don't need 'where' key in where clause.
```
Customer.count({firstname: {like: value + "%"}}, function (err, count) {
  sync(err, null, count);
});
```

Check this document:
https://apidocs.strongloop.com/loopback/#persistedmodel-count

**Comment by Kr0san89** [comment]
Thanks a lot. Wasn't clear because it was linked to the where filter page, where it is descripted in general. 
Wouldn't it be good to have the same parameter as on the find()? I guess it would be more intuitive?
thanks

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
The docs do have distinct explanation of the two kinds of where clauses:
- [Where clause for queries](https://docs.strongloop.com/display/LB/Where+filter#Wherefilter-Whereclauseforqueries)
- [Where clause for other methods](https://docs.strongloop.com/display/LB/Where+filter#Wherefilter-Whereclauseforothermethods)

However, I agree it would be better to link directly to those sections from the API docs, rather than to the top-level article where it might not be clear.  I'll fix the API docs.
