### ISSUE TITLE
hasManyThrough scope intermediate table

### ISSUE THREAD

**Issue by mbouclas** [strongloop/loopback-connector-mysql#142]
Is there a way to get the pivot table on a hasManyThrough query? Better yet, apply some filter or sort to it. A typical example 

```
Table products
id,title

Table categories
id,title

table products_categories
productsId, categoriesId, orderBy, main

```

So, in the above scenario, say you want to get all categories of product X that are (main = true) or you want to sort the the product categories by orderBy.

What happens now is a first SELECT on products to get the product data, a second SELECT on products_categories to get the categoriesId and a final SELECT on categories to get the actual categories. Ideally, filters and sort should be applied to the 2nd SELECT like 

```
SELECT `id`,`productsId`,`categoriesId`,`orderBy`,`main` FROM `products_categories` 

WHERE `productsId` IN (180) WHERE main = 1 ORDER BY `orderBy` DESC
```

Another typical example would be wanting to order the product images based on the order the user wants them to

so you would have a products_images table

```
id,image,productsID,orderBy
```

and you would want to

```
SELECT from products_images WHERE productsId In (180) ORDER BY orderBy ASC

```

Here is the relationship needed for an intermediate table to get what i need based on my schema.

```
Products.hasMany(Images,
    {
        as: "Images",
        "foreignKey": "productsId",
        "through": ProductsImagesItems,
        scope: function (inst, filter) {
            return {active: 1};
        }
    });
```

Thing is the scope function is giving me access to the final result and not to the intermediate table.

Is that even possible?

**Comment by jannyHou** [comment]
@mbouclas I believe this is the same feature as https://github.com/strongloop/loopback-datasource-juggler/issues/941

Scenario:
`Mymodel` hasMany `relatedModel` through `throughModel`

Technically, we are able to apply filters on both `throughModel` and `relatedModel`, but IMO the tricky thing is they might run into conflict.

e.g.: you use two filters:
```js
{
  throughFilter: {limit: 3},
  relatedFilter: {order: name}
}
```
will be fine, it returns you 3 result which are ordered by relatedModel's name.
But think of
```js
{
  throughFilter: {order: date},
  relatedFilter: {order: name}
}
```
loopback will be confused with which property should I order by.

I close issue here as a dup of https://github.com/strongloop/loopback-datasource-juggler/issues/941. And this feature is also good to discuss in loopback-datasource-juggler because if we support it, that's the related repo to have code change.
