### ISSUE TITLE
model filter with inq: [null, 1] breaks

### ISSUE THREAD

**Issue by stringbeans** [strongloop/loopback-connector-mysql#221]
If I'm doing a model filter with something like...

Model.find({where: {id: {inq: [null, 1]}}}) the sql generated will build something that looks like this...

```
select <fields>
from model
where model.id in (DEFAULT, 1)
```

this is erroneous sql

Edit: this is happening on the latest release of this connector as well as previous releases

**Comment by jannyHou** [comment]
@stringbeans If `id` is your primary key, it could not be null right?

**Comment by stringbeans** [comment]
hi @jannyHou !

its an erroneous filter i admit, but i feel that the connector should gracefully handle this by removing the null values from the array or replacing the 'DEFAULT' keyword in the query with the actual null value. does that make sense?

**Comment by jannyHou** [comment]
ah @stringbeans I see. 

>  but i feel that the connector should gracefully handle this by removing the null values from the array

`inq` is not only used in primary key, for other columns it's fine to fetch instances with value `null`. 
So "removing the null values" need additional check of keyType(primary/non-primary), not a very necessary work to add IMO :p 

And I think it's fine to let driver discover an invalid query and return warning, as long as it doesn't terminate the app.

I label it as a feature, not sure will we have priority on it :p

**Comment by stringbeans** [comment]
@jannyHou yeah i actually dont like the solution of removing the null values either

at the end of the day, passing null values to the inq filter should still create valid SQL. that's the issue im logging here. suppose you do:

```
Student.find({
  where: {
    studentId: {
      inq: [1, null, 3]
    }
})
```

the eventual SQL query created from that is:

```
SELECT *
FROM student
WHERE student.student_id IN (1, DEFAULT, 3)
```

this is the bug. it actually creates an invalid SQL statement from passing null into the inq filter. 

regardless of the reasons why a null value would be passed into the inq filter, it should still produce valid SQL.

**Comment by jannyHou** [comment]
> regardless of the reasons why a null value would be passed into the inq filter, it should still produce valid SQL.

true :)

**Comment by Zvax** [comment]
I would chime in and argue that not only should a null value being passed still produce valid sql, but also it should actually search for null values. Querying a table for rows where a value `IS NULL` is a valid requirement when dealing with parent/children hierarchies, where the top level elements would have a null parentId.

Which is actually my use case and how I stumbled here. I have a model that can belong to another entry of that specific model. The "top level" ones have null as their "belongsTo" field, because they do not belong to anyone. I want to query only these entries, the "top level" entries, through the rest api: `/api/stuff?filter[include]=children&[where][stuffId]=null`.

This is a bit orthogonal, as the original issue was about the json search, if there is a more relevant place where I should post this I would be grateful to be informed, this is the closest issue I could find.

<pre>
{
  "name": "stuff",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "description": {
      "type": "string",
      "required": true
    },
    "status": {
      "type": "number",
      "required": true,
      "default": 1
    }
  },
  "validations": [],
  "relations": {
    "children": {
      "type": "hasMany",
      "model": "stuff",
      "foreignKey": ""
    },
    "parent": {
      "type": "belongsTo",
      "model": "stuff",
      "foreignKey": "stuffId"
    }
  },
  "acls": [],
  "methods": {}
}
</pre>

**Comment by b-admike** [comment]
@stringbeans This issue should be resolved in the next release of this connector. Thank you.
