### ISSUE TITLE
Provide a way to specify table and field naming convention with automigrate/autoupdate

### ISSUE THREAD

**Issue by simoami** [strongloop/loopback-connector-mysql#57]
Having worked on various enterpise projects in the pase it's odd for me to see camel-cased table names and table field names. it is more common to see underlined syntax, as is also found in loopback-connector-mysql source code.

| namingStrategy | description |
| --- | --- |
| model | same as the linked model (default) |
| camelcase | camel-cased. first character lowercase |
| underscore | all lowercase. underscore as separator |

It would be great to be able to specify the desired naming convention as an optional setting to preserve backward compatibility with existing projects and for new projects to have the chance to use proper naming conventions.

**Comment by kevintechie** [comment]
I'll also add that the discoverSchema suffers from this problem as well. This method will translate snake case (w/ underscore) names to camelcase for use in the JavaScript models, but loopback will not translate in reverse when using those models to access the database.

This is very frustrating when trying to maintain consistency in both the JavaScript and database domains. In addition, the auto-discovery tools are not useful if they generate invalid results.

**Comment by mnvx** [comment]
Mapping can be described in model definition.

Example, `/common/models/model.json`:

```
"locationId":{
    "type":"String",
    "required":true,
    "length":20,
    "mysql":
    {
        "columnName":"LOCATION_ID",
        "dataType":"VARCHAR2",
        "dataLength":20,
        "nullable":"N"
    }
}
```
More about mapping: https://docs.strongloop.com/display/public/LB/MySQL+connector#MySQLconnector-Usingthedatatypefield/columnoptionwithMySQL

**Comment by GuilhermeMedeiros** [comment]
the datasource.autoupdate **ignores** the columnName though

**Comment by james-relyea** [comment]
I'd be willing to work on this if there were an agreed upon implementation strategy.

**Comment by ajmalmsali** [comment]
@james-relyea is there any update on this?

**Comment by DennisM330** [comment]
In APIC v5.0.2.0, the designer toolkit takes a column_name with "_" and converts to camelcase when discovering a model from MySQL. This causes and error when exploring the API and testing in the toolkit. Need a way to tell it to preserve DB table column names,

**Comment by ketansp** [comment]
Any updates? How can I specify table name?

**Comment by chillyprig** [comment]
I need this feature too. +1

**Comment by macogala** [comment]
In model.discoverSchema() you can provide options.nameMapper and specify a custom nameMapper(type, name) function to map your model names in your preferred way. For eg, if you want to keep your DB style, you can just do:

```
options.nameMapper =function mapName(type, name){ return name; };
datasource.discoverSchema(schema_name, options, callback);
```

**Comment by ariskemper** [comment]
This issue would be more for loopback-datasource-juggler, since all operations are handled there.

@macogala is right and it could be done via nameMapper, but would be good to have option in discoverSchema, where is possible to define naming strategy.

@simoami  I suggest that we handle both naming strategy for Camel Case like upper and lower camel case. With those naming strategies, we probably cover all scenarios.

namingStrategy| Description
------------ | -------------
model | same as the linked model (default)
lowerCamelCase | camel-cased. first character lowercase
upperCamelCase | camel-cased. first character uppercase
underscore | all lowercase. underscore as separator

**Comment by aaalsubaie** [comment]
any update on this?

**Comment by go2smartphone** [comment]
any progreess?

**Comment by lehni** [comment]
I've managed to make this work from a bootstript, e.g. `00-database.js` for postgresql, but looking at https://github.com/strongloop/loopback-connector, I don't see a reason why it shouldn't work here either:

```js
const underscore = require('...')

module.exports = function (app) {
  for (let source of Object.values(app.dataSources)) {
    source.connector.dbName = underscore
  }
}
```

`dbName()`, if present is being used for the processing of the names of tables and columns, e.g.:

https://github.com/strongloop/loopback-connector/blob/ffa776cf6a0e401ee0427ce42e9f5e24cb124bdf/lib/sql.js#L351

So I believe that https://github.com/strongloop/loopback-connector is then also the place where we should implement this if it was to be done through a settings switch. I am happy to create a PR for it.

Proposed syntax, based on the above discussion:

`datasources.json`:
```json
{
  "source": {
    "name": "source",
    "connector": "postgresql",
    "host": "localhost",
    "port": 5432,
    "user": "name",
    "password": "",
    "database": "database",
    "namingStrategy": "underscore"
  }
}
```

**Comment by lehni** [comment]
Update: I just implemented this proposal through the boot-script, and it works:
#### 00-database.js
```js
const underscore = require('...')

const namingStrategies = {
  model: val => val,
  underscore,
  lowercase: val => val ? val.toLowerCase() : val,
  uppercase: val => val ? val.toUpperCase() : val
}

// Override Connector.prototype.dbName in loopback-connector to support
// settings.namingStrategies.
module.exports = function (app) {
  for (let source of Object.values(app.dataSources)) {
    const connector = source.connector
    const strategy = connector.settings.namingStrategy
    const dbName = typeof strategy === 'function' ? strategy
      : namingStrategies[strategy]
    if (dbName) {
      connector.dbName = dbName
    }
  }
}
```

#### datasources.json
```json
{
  "source": {
    "name": "source",
    "connector": "postgresql",
    "host": "localhost",
    "port": 5432,
    "user": "name",
    "password": "",
    "database": "database",
    "namingStrategy": "underscore"
  }
}
```

I've added "lowercase" because that's what loopback-connector-postgresql uses by default:
https://github.com/strongloop/loopback-connector-postgresql/blob/ef6466063d128c3a381b637c59bbb66b71e94890/lib/postgresql.js#L325
 
Let's use this as the base for discussion to create a PR on loopback-connector

**Comment by lehni** [comment]
@ariskemper did you see my proposal above? This already works for me...

**Comment by lehni** [comment]
One more thought: 

I am not sure if `model` is the right name, since it's also affecting column names. What else could it be?

**Comment by lehni** [comment]
@kjdelisle @bajtos I think this should be addressed. It's a valid point, and I am not super keen on keeping my workaround in https://github.com/strongloop/loopback-connector-mysql/issues/57#issuecomment-313635186

I can take care of it, but would be interested in hearing your thoughts.

**Comment by bajtos** [comment]
@lehni your proposal looks reasonable to me, at least as far as I can tell from my limited knowledge of this part of LoopBack codebase.

IIUC, the new datasource/connector config option `namingStrategy` can be implemented in a backward-compatible way where `undefined` means "use the default behavior as of 2017-09-14", therefore existing applications won't be affected and any possible shortcomings of your proposal will affect only users of this new feature.

Let's wait for @kjdelisle to express his thoughts. 

> There is currently no way to distinguish tables and columns in calls dbName(), so I wonder if this would make sense? I would also suggest to use camelCase for lower and pascalCase for upper, perhaps.

I am afraid this is beyond my knowledge. Perhaps we can improve our codebase to pass a new argument to `dbName` with a value `table` or `column` in order to allow custom functions to know what kind of database name they are building?

OTOH, I would expect people to follow the same naming style for both table and column names - if my table is called `USER_PROFILES` then I'd expect column names like `ZIP_CODE` (or `user_profiles` table with `zip_code` column), so I think it should be ok to use the same naming strategy for both columns and tables for now. We can always improve this later if needed.

---

As I was reading through the discussion, I think this solution will work only for people creating their models manually, but won't address the following complain:

> In APIC v5.0.2.0, the designer toolkit takes a column_name with "_" and converts to camelcase when discovering a model from MySQL. This causes an error when exploring the API and testing in the toolkit. Need a way to tell it to preserve DB table column names,

This one may need its own fix too:

> the `datasource.autoupdate` ignores the `columnName` though

**Comment by lehni** [comment]
@kjdelisle I am curious to hear your thoughts on this. I'd like to start addressing this, as my component fix above has other problems, mainly that mixins get initiated before components, so at that point, `dbName()` is still the wrong version.

I would suggest to simply call the field `naming` to keep things simple, perhaps?

And we still need to discuss, which possible values it should support. I would suggest:

- `'default'`: The same as not defining it, and whatever the specific connector did so far
- `'untransformed'`: The same as `model` above, but more specific about what's happening.
- `'lowercase'`: All lowercase with no separator
- `'uppercase'`: All uppercase with no separator
- `'underscore'`: All lowercase with underscore as separator

Once we agree, I'll create a PR on `loopback-connector` and some of the other connectors that override `dbName()` currently, e.g. `loopback-connector-postgresql`

**Comment by lehni** [comment]
And we could decide to implement this in`loopback` also. Here is how I have it currently implemented as a monkey-patch of `app.dataSource()`:

#### server.js
```js
const underscore = require('...')

const app = loopback()

// https://github.com/strongloop/loopback-connector-mysql/issues/57#issuecomment-313635186
const {dataSource} = app
app.dataSource = function (name, config) {
  const ds = dataSource.call(this, name, config)
  const {naming} = config
  const namingStrategies = {
    untransformed: val => val,
    underscore,
    lowercase: val => val.toLowerCase(),
    uppercase: val => val.toUpperCase(),
    'default': null
  }
  const dbName = isFunction(naming) ? naming : namingStrategies[naming]
  if (dbName) {
    ds.connector.dbName = dbName
  }
  return ds
}
```

#### datasources.json
```json
{
  "source": {
    "name": "source",
    "connector": "mysql",
    "host": "localhost",
    "port": 3306,
    "user": "name",
    "password": "",
    "database": "database",
    "naming": "underscore"
  }
}
```

**Comment by lehni** [comment]
One last observation: Adding this to `app.dataSource()` in `loopback` may be easier than to `Connector.prototype.dbName()` in `loopback-connector`, since some connectors already define their own to have a different default behaviour (e.g. ` loopback-connector-postgresql`), and `loopback-connector` doesn't define a default `dbName()`. If we now added this functionality in `Connector.prototype.dbName()`, it would get overridden by other connectors and we would have to patch those. But if it happens in `app.dataSource()`, and only if `naming` was set, then it would work with any connector out of the box.

**Comment by ketansp** [comment]
+1 for this feature

**Comment by ketansp** [comment]
To unmark it as stale

**Comment by JSilversun** [comment]
Why did you close this issue? I think is really important to separate the naming conventions between database and application. +1 to reopen.

**Comment by regeechacko** [comment]
Any known solution for this issue?
Even in loopback 4 this option is not available or working?
Is there any working example with JSON based model file?

**Comment by sureshkodur** [comment]
Hello, Any update on this? I have a similar issue.

**Comment by agnes512** [comment]
please check #3343(https://github.com/strongloop/loopback-next/issues/3343)

**Comment by Clemens-E** [comment]
If I get this right, this Issue is 5 Years old, and there is still no solution to this?
